package io.github.bitlinker.kradiobrowser.api.responses

import io.ktor.http.ContentType
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders

object MockEngineResponderChecks : MockEngineResponder {
    override val body: String = """
        [
            {
                "stationuuid": "43cf1869-6849-4fff-954d-fdbad6e412e2",
                "checkuuid": "e6314e34-a956-4209-83eb-176d06835de3",
                "source": "fi1",
                "codec": "MP3",
                "bitrate": 128,
                "hls": 0,
                "ok": 1,
                "timestamp_iso8601": "2025-05-24T15:03:47Z",
                "timestamp": "2025-05-24 15:03:47",
                "urlcache": "http://stream.dancewave.online:8080/dance.mp3",
                "metainfo_overrides_database": 1,
                "public": 0,
                "name": "Dance Wave!",
                "description": "All about Dance from 2000 till today!",
                "tags": "Club Dance Electronic House Trance",
                "countrycode": null,
                "homepage": "https://dancewave.online",
                "favicon": "https://dancewave.online/dw_logo.png",
                "loadbalancer": "https://dancewave.online/dance.mp3",
                "do_not_index": null,
                "countrysubdivisioncode": null,
                "server_software": "cloudflare",
                "sampling": 44100,
                "timing_ms": 413,
                "languagecodes": "",
                "ssl_error": 0,
                "geo_lat": null,
                "geo_long": null
            },
            {
                "stationuuid": "43cf1869-6849-4fff-954d-fdbad6e412e2",
                "checkuuid": "f97c1781-8a7c-4b80-8fbb-ffb296adb274",
                "source": "de1",
                "codec": "MP3",
                "bitrate": 128,
                "hls": 0,
                "ok": 1,
                "timestamp_iso8601": "2025-05-25T07:57:26Z",
                "timestamp": "2025-05-25 07:57:26",
                "urlcache": "http://stream.dancewave.online:8080/dance.mp3",
                "metainfo_overrides_database": 1,
                "public": 0,
                "name": "Dance Wave!",
                "description": "All about Dance from 2000 till today!",
                "tags": "Club Dance Electronic House Trance",
                "countrycode": null,
                "homepage": "https://dancewave.online",
                "favicon": "https://dancewave.online/dw_logo.png",
                "loadbalancer": "https://dancewave.online/dance.mp3",
                "do_not_index": null,
                "countrysubdivisioncode": null,
                "server_software": "cloudflare",
                "sampling": 44100,
                "timing_ms": 254,
                "languagecodes": "",
                "ssl_error": 0,
                "geo_lat": null,
                "geo_long": null
            },
            {
                "stationuuid": "43cf1869-6849-4fff-954d-fdbad6e412e2",
                "checkuuid": "6d9eedfe-c958-4a5e-b13c-4c5a1f79ec2c",
                "source": "de2",
                "codec": "MP3",
                "bitrate": 128,
                "hls": 0,
                "ok": 1,
                "timestamp_iso8601": "2025-05-25T08:45:11Z",
                "timestamp": "2025-05-25 08:45:11",
                "urlcache": "http://onair.dancewave.online:8080/dance.mp3",
                "metainfo_overrides_database": 1,
                "public": 0,
                "name": "Dance Wave!",
                "description": "All about Dance from 2000 till today!",
                "tags": "Club Dance Electronic House Trance",
                "countrycode": null,
                "homepage": "https://dancewave.online",
                "favicon": "https://dancewave.online/dw_logo.png",
                "loadbalancer": "https://dancewave.online/dance.mp3",
                "do_not_index": null,
                "countrysubdivisioncode": null,
                "server_software": "Icecast",
                "sampling": 44100,
                "timing_ms": 212,
                "languagecodes": "",
                "ssl_error": 0,
                "geo_lat": null,
                "geo_long": null
            },
            {
                "stationuuid": "43cf1869-6849-4fff-954d-fdbad6e412e2",
                "checkuuid": "67f8fbc8-53b4-48c7-a3c2-e2b769081031",
                "source": "fi1",
                "codec": "MP3",
                "bitrate": 128,
                "hls": 0,
                "ok": 1,
                "timestamp_iso8601": "2025-05-25T15:05:15Z",
                "timestamp": "2025-05-25 15:05:15",
                "urlcache": "http://stream.dancewave.online:8080/dance.mp3",
                "metainfo_overrides_database": 1,
                "public": 0,
                "name": "Dance Wave!",
                "description": "All about Dance from 2000 till today!",
                "tags": "Club Dance Electronic House Trance",
                "countrycode": null,
                "homepage": "https://dancewave.online",
                "favicon": "https://dancewave.online/dw_logo.png",
                "loadbalancer": "https://dancewave.online/dance.mp3",
                "do_not_index": null,
                "countrysubdivisioncode": null,
                "server_software": "cloudflare",
                "sampling": 44100,
                "timing_ms": 378,
                "languagecodes": "",
                "ssl_error": 0,
                "geo_lat": null,
                "geo_long": null
            }
        ]
    """.trimIndent()

    override val headers = Headers.build {
        append(HttpHeaders.ContentType, ContentType.Application.Json.toString())
    }
}